---
- hosts: server
  become: true
  tasks:

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="192.168.86.165" --pod-network-cidr=172.16.0.0/16
