---
- hosts: worker
  become: true
  tasks:

   - name: Copy the join command to server location
     copy: src=join-command dest=/tmp/join-command.sh mode=0777

   - name: Join the node to cluster
     command: /bin/bash /tmp/join-command.sh
