---
- hosts: server, worker
  become: true
  tasks:

   - name: Add an apt signing key for Kubernetes
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: Adding apt repository for Kubernetes
     apt_repository:
       repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
       state: present
       filename: kubernetes.list

   - name: Install Kubernetes binaries
     apt:
       name: "{{ packages }}"
       state: present
       update_cache: yes
     vars:
       packages:
         - kubelet=1.24.7-00
         - kubeadm=1.24.7-00
         - kubectl=1.24.6-00

   - name: Hold kubelet
     dpkg_selections:
       name: kubelet
       selection: hold
   - name: Hold kubectl
     dpkg_selections:
       name: kubectl
       selection: hold
   - name: Hold kubeadm
     dpkg_selections:
       name: kubeadm
       selection: hold

   - name: Configure node ip
     lineinfile:
       path: /etc/default/kubelet
       line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

   - name: Restart kubelet
     service:
       name: kubelet
       daemon_reload: yes
       state: restarted
